name: CI

on:
  schedule:
    - cron: "4 23 * * 0"
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0

      - name: Run a one-line script
        run: curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@main/${{ github.event.repository.name }}"
